"""empty message

Revision ID: 96da6de4fede
Revises: 8e8a6da60fab
Create Date: 2025-01-03 15:45:07.972617

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96da6de4fede'
down_revision = '8e8a6da60fab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_favorites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('people_id', sa.Integer(), nullable=True),
    sa.Column('planet_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['people_id'], ['people.id'], ),
    sa.ForeignKeyConstraint(['planet_id'], ['planet.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_favorites')
    # ### end Alembic commands ###
